# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MotionClientsHVNcT.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QGroupBox, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(534, 784)
        MainWindow.setAutoFillBackground(False)
        self.GroupBox_Serial = QGroupBox(MainWindow)
        self.GroupBox_Serial.setObjectName(u"GroupBox_Serial")
        self.GroupBox_Serial.setEnabled(True)
        self.GroupBox_Serial.setGeometry(QRect(270, 60, 250, 298))
        self.PushButton_PortConnect = QPushButton(self.GroupBox_Serial)
        self.PushButton_PortConnect.setObjectName(u"PushButton_PortConnect")
        self.PushButton_PortConnect.setGeometry(QRect(30, 240, 90, 22))
        self.PushButton_PortDisconnect = QPushButton(self.GroupBox_Serial)
        self.PushButton_PortDisconnect.setObjectName(u"PushButton_PortDisconnect")
        self.PushButton_PortDisconnect.setGeometry(QRect(130, 240, 90, 22))
        self.flowControlLabel = QLabel(self.GroupBox_Serial)
        self.flowControlLabel.setObjectName(u"flowControlLabel")
        self.flowControlLabel.setGeometry(QRect(30, 210, 190, 30))
        self.dataBitsLabel = QLabel(self.GroupBox_Serial)
        self.dataBitsLabel.setObjectName(u"dataBitsLabel")
        self.dataBitsLabel.setGeometry(QRect(30, 123, 190, 22))
        self.stopBitsLabel = QLabel(self.GroupBox_Serial)
        self.stopBitsLabel.setObjectName(u"stopBitsLabel")
        self.stopBitsLabel.setGeometry(QRect(30, 181, 190, 22))
        self.parityLabel = QLabel(self.GroupBox_Serial)
        self.parityLabel.setObjectName(u"parityLabel")
        self.parityLabel.setGeometry(QRect(30, 152, 190, 22))
        self.baudRateLabel = QLabel(self.GroupBox_Serial)
        self.baudRateLabel.setObjectName(u"baudRateLabel")
        self.baudRateLabel.setGeometry(QRect(30, 94, 190, 22))
        self.statusLabel = QLabel(self.GroupBox_Serial)
        self.statusLabel.setObjectName(u"statusLabel")
        self.statusLabel.setGeometry(QRect(30, 70, 370, 22))
        self.PushButton_Settings = QPushButton(self.GroupBox_Serial)
        self.PushButton_Settings.setObjectName(u"PushButton_Settings")
        self.PushButton_Settings.setGeometry(QRect(80, 270, 90, 22))
        self.portNameLabel = QLabel(self.GroupBox_Serial)
        self.portNameLabel.setObjectName(u"portNameLabel")
        self.portNameLabel.setGeometry(QRect(30, 40, 370, 22))
        self.GroupBox_Move = QGroupBox(MainWindow)
        self.GroupBox_Move.setObjectName(u"GroupBox_Move")
        self.GroupBox_Move.setGeometry(QRect(10, 208, 251, 249))
        self.LineEdit_Distance = QLineEdit(self.GroupBox_Move)
        self.LineEdit_Distance.setObjectName(u"LineEdit_Distance")
        self.LineEdit_Distance.setGeometry(QRect(20, 40, 113, 22))
        self.LineEdit_Velocity = QLineEdit(self.GroupBox_Move)
        self.LineEdit_Velocity.setObjectName(u"LineEdit_Velocity")
        self.LineEdit_Velocity.setGeometry(QRect(20, 90, 113, 22))
        self.LineEdit_Accel = QLineEdit(self.GroupBox_Move)
        self.LineEdit_Accel.setObjectName(u"LineEdit_Accel")
        self.LineEdit_Accel.setGeometry(QRect(20, 140, 113, 22))
        self.LineEdit_Decel = QLineEdit(self.GroupBox_Move)
        self.LineEdit_Decel.setObjectName(u"LineEdit_Decel")
        self.LineEdit_Decel.setGeometry(QRect(20, 190, 113, 22))
        self.PushButton_Move = QPushButton(self.GroupBox_Move)
        self.PushButton_Move.setObjectName(u"PushButton_Move")
        self.PushButton_Move.setGeometry(QRect(20, 220, 80, 22))
        self.PushButton_Abort = QPushButton(self.GroupBox_Move)
        self.PushButton_Abort.setObjectName(u"PushButton_Abort")
        self.PushButton_Abort.setGeometry(QRect(150, 220, 80, 22))
        self.IPLabel_2 = QLabel(self.GroupBox_Move)
        self.IPLabel_2.setObjectName(u"IPLabel_2")
        self.IPLabel_2.setGeometry(QRect(20, 20, 140, 22))
        self.IPLabel_3 = QLabel(self.GroupBox_Move)
        self.IPLabel_3.setObjectName(u"IPLabel_3")
        self.IPLabel_3.setGeometry(QRect(20, 70, 130, 22))
        self.IPLabel_4 = QLabel(self.GroupBox_Move)
        self.IPLabel_4.setObjectName(u"IPLabel_4")
        self.IPLabel_4.setGeometry(QRect(20, 120, 130, 22))
        self.IPLabel_5 = QLabel(self.GroupBox_Move)
        self.IPLabel_5.setObjectName(u"IPLabel_5")
        self.IPLabel_5.setGeometry(QRect(20, 170, 140, 22))
        self.GroupBox_Jog = QGroupBox(MainWindow)
        self.GroupBox_Jog.setObjectName(u"GroupBox_Jog")
        self.GroupBox_Jog.setGeometry(QRect(10, 60, 251, 139))
        self.lineEdit_7 = QLineEdit(self.GroupBox_Jog)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(20, 80, 113, 22))
        self.IPLabel_6 = QLabel(self.GroupBox_Jog)
        self.IPLabel_6.setObjectName(u"IPLabel_6")
        self.IPLabel_6.setGeometry(QRect(20, 60, 150, 22))
        self.pushButton_3 = QPushButton(self.GroupBox_Jog)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(20, 110, 80, 22))
        self.pushButton_4 = QPushButton(self.GroupBox_Jog)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(150, 110, 80, 22))
        self.checkBox_2 = QCheckBox(self.GroupBox_Jog)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(20, 30, 91, 20))
        self.GroupBox_Home = QGroupBox(MainWindow)
        self.GroupBox_Home.setObjectName(u"GroupBox_Home")
        self.GroupBox_Home.setGeometry(QRect(270, 398, 251, 59))
        self.pushButton_5 = QPushButton(self.GroupBox_Home)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(150, 30, 80, 22))
        self.pushButton_6 = QPushButton(self.GroupBox_Home)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(20, 30, 80, 22))
        self.IPLabel_7 = QLabel(MainWindow)
        self.IPLabel_7.setObjectName(u"IPLabel_7")
        self.IPLabel_7.setGeometry(QRect(300, 370, 61, 20))
        self.LineEdit_Position = QLineEdit(MainWindow)
        self.LineEdit_Position.setObjectName(u"LineEdit_Position")
        self.LineEdit_Position.setGeometry(QRect(370, 370, 120, 20))
        self.GroupBox_Limits = QGroupBox(MainWindow)
        self.GroupBox_Limits.setObjectName(u"GroupBox_Limits")
        self.GroupBox_Limits.setGeometry(QRect(10, 468, 511, 99))
        self.IPLabel_8 = QLabel(self.GroupBox_Limits)
        self.IPLabel_8.setObjectName(u"IPLabel_8")
        self.IPLabel_8.setGeometry(QRect(40, 30, 71, 22))
        self.IPLabel_9 = QLabel(self.GroupBox_Limits)
        self.IPLabel_9.setObjectName(u"IPLabel_9")
        self.IPLabel_9.setGeometry(QRect(40, 60, 91, 22))
        self.IPLabel_10 = QLabel(self.GroupBox_Limits)
        self.IPLabel_10.setObjectName(u"IPLabel_10")
        self.IPLabel_10.setGeometry(QRect(390, 60, 91, 22))
        self.IPLabel_10.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.IPLabel_11 = QLabel(self.GroupBox_Limits)
        self.IPLabel_11.setObjectName(u"IPLabel_11")
        self.IPLabel_11.setGeometry(QRect(410, 30, 71, 22))
        self.IPLabel_11.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.GroupBox_Sequences = QGroupBox(MainWindow)
        self.GroupBox_Sequences.setObjectName(u"GroupBox_Sequences")
        self.GroupBox_Sequences.setGeometry(QRect(10, 580, 511, 79))
        self.label_3 = QLabel(self.GroupBox_Sequences)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(25, 40, 80, 22))
        self.comboBox_3 = QComboBox(self.GroupBox_Sequences)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(100, 40, 79, 22))
        self.pushButton_7 = QPushButton(self.GroupBox_Sequences)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(280, 40, 80, 22))
        self.pushButton_8 = QPushButton(self.GroupBox_Sequences)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(410, 40, 80, 22))
        self.checkButton = QPushButton(MainWindow)
        self.checkButton.setObjectName(u"checkButton")
        self.checkButton.setGeometry(QRect(10, 670, 80, 20))
        self.GroupBox_Motor = QGroupBox(MainWindow)
        self.GroupBox_Motor.setObjectName(u"GroupBox_Motor")
        self.GroupBox_Motor.setGeometry(QRect(10, 10, 510, 40))
        self.CheckBox_EnableMotor = QCheckBox(self.GroupBox_Motor)
        self.CheckBox_EnableMotor.setObjectName(u"CheckBox_EnableMotor")
        self.CheckBox_EnableMotor.setGeometry(QRect(10, 10, 111, 20))
        self.label = QLabel(self.GroupBox_Motor)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(160, 10, 80, 22))
        self.ComboBox_MotorType = QComboBox(self.GroupBox_Motor)
        self.ComboBox_MotorType.addItem("")
        self.ComboBox_MotorType.addItem("")
        self.ComboBox_MotorType.setObjectName(u"ComboBox_MotorType")
        self.ComboBox_MotorType.setGeometry(QRect(240, 10, 79, 22))
        self.label_2 = QLabel(self.GroupBox_Motor)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(350, 10, 30, 22))
        self.ComboBox_AxisSelect = QComboBox(self.GroupBox_Motor)
        self.ComboBox_AxisSelect.addItem("")
        self.ComboBox_AxisSelect.addItem("")
        self.ComboBox_AxisSelect.addItem("")
        self.ComboBox_AxisSelect.setObjectName(u"ComboBox_AxisSelect")
        self.ComboBox_AxisSelect.setGeometry(QRect(390, 10, 79, 22))

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Dialog", None))
        self.GroupBox_Serial.setTitle(QCoreApplication.translate("MainWindow", u"USB-to-Serial", None))
        self.PushButton_PortConnect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.PushButton_PortDisconnect.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
        self.flowControlLabel.setText(QCoreApplication.translate("MainWindow", u"Flow control:", None))
        self.dataBitsLabel.setText(QCoreApplication.translate("MainWindow", u"Data bits:", None))
        self.stopBitsLabel.setText(QCoreApplication.translate("MainWindow", u"Stop bits:", None))
        self.parityLabel.setText(QCoreApplication.translate("MainWindow", u"Parity:", None))
        self.baudRateLabel.setText(QCoreApplication.translate("MainWindow", u"BaudRate:", None))
        self.statusLabel.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.PushButton_Settings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.portNameLabel.setText(QCoreApplication.translate("MainWindow", u"Port Name:", None))
        self.GroupBox_Move.setTitle(QCoreApplication.translate("MainWindow", u"Move", None))
        self.PushButton_Move.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.PushButton_Abort.setText(QCoreApplication.translate("MainWindow", u"Abort", None))
        self.IPLabel_2.setText(QCoreApplication.translate("MainWindow", u"Distance (counts)", None))
        self.IPLabel_3.setText(QCoreApplication.translate("MainWindow", u"Velocity (counts/sec)", None))
        self.IPLabel_4.setText(QCoreApplication.translate("MainWindow", u"Accel (counts/sec^2)", None))
        self.IPLabel_5.setText(QCoreApplication.translate("MainWindow", u"Decel (counts/sec^2)", None))
        self.GroupBox_Jog.setTitle(QCoreApplication.translate("MainWindow", u"Jog", None))
        self.IPLabel_6.setText(QCoreApplication.translate("MainWindow", u"Jog Velocity (counts/sec)", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Positive", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Negative", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"Activate Jog", None))
        self.GroupBox_Home.setTitle(QCoreApplication.translate("MainWindow", u"Home", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Abort", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.IPLabel_7.setText(QCoreApplication.translate("MainWindow", u"Position", None))
        self.LineEdit_Position.setText("")
        self.GroupBox_Limits.setTitle(QCoreApplication.translate("MainWindow", u"Limit Sensors", None))
        self.IPLabel_8.setText(QCoreApplication.translate("MainWindow", u"Neg. Limit", None))
        self.IPLabel_9.setText(QCoreApplication.translate("MainWindow", u"Neg. SW Limit", None))
        self.IPLabel_10.setText(QCoreApplication.translate("MainWindow", u"Pos. SW Limit", None))
        self.IPLabel_11.setText(QCoreApplication.translate("MainWindow", u"Pos. Limit", None))
        self.GroupBox_Sequences.setTitle(QCoreApplication.translate("MainWindow", u"Sequences", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Sequence", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.checkButton.setText(QCoreApplication.translate("MainWindow", u"Check", None))
        self.GroupBox_Motor.setTitle("")
        self.CheckBox_EnableMotor.setText(QCoreApplication.translate("MainWindow", u"Enable Motor", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Motor Type:", None))
        self.ComboBox_MotorType.setItemText(0, QCoreApplication.translate("MainWindow", u"Servo", None))
        self.ComboBox_MotorType.setItemText(1, QCoreApplication.translate("MainWindow", u"Stepper", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Axis: ", None))
        self.ComboBox_AxisSelect.setItemText(0, QCoreApplication.translate("MainWindow", u"X", None))
        self.ComboBox_AxisSelect.setItemText(1, QCoreApplication.translate("MainWindow", u"Y", None))
        self.ComboBox_AxisSelect.setItemText(2, QCoreApplication.translate("MainWindow", u"Z", None))

    # retranslateUi

